name: examace
description: A dark-themed study hub for notes, PYQs, and trackers.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#1F1F1F"
  color_dark: "#1F1F1F"
  android_12:
    color: "#1F1F1F"
    color_dark: "#1F1F1F"
  android: true
  ios: true
  web: true
